language: objective-c
os: osx
python:
  - "3.4"
before_install:
  - brew update
  - brew install python3
  - which python3
  - python3 --version
# Upgrade pip
  - pip3 install --upgrade pip setuptools
  - brew install qt5
  - brew install pyqt5
  - brew install portaudio
# command to install dependencies
install:
  - pip3 install --allow-external pyaudio --allow-unverified pyaudio -r requirements.txt
  - pip3 install -U py2app
# command to run tests
# script: nosetests