language: objective-c
os: osx
python:
  - "3.4"
before_install:
  - brew update
  - brew install python3
# make brews python the system default
  - brew link --overwrite python3
  - which python
  - python --version
# Upgrade pip
  - pip install --upgrade pip
  - brew install qt5
  - brew install portaudio
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U py2app
# command to run tests
# script: nosetests