language: objective-c
os: osx
python:
  - "3.4"
before_install:
  - brew update
  - brew install python3
  - which python3
  - python3 --version
# Upgrade pip
  - pip3 install --upgrade pip setuptools
  - brew install qt5
  - brew install pyqt5
  - brew install portaudio
  - brew info coreutils # for the timeout command below
# command to install dependencies
install:
  - pip3 install --allow-external pyaudio --allow-unverified pyaudio -r requirements.txt
  - pip3 install -U py2app
# command to run tests
script:
 - python3 -c "from PyQt5 import QtCore; print(\"Qt \" + QtCore.qVersion())"
 - python3 -c "from PyQt5 import QtCore; print(\"PyQt \" + QtCore.PYQT_VERSION_STR)"
 - python3 -c "import pyaudio; print(\"PyAudio \" + pyaudio.__version__)"
 - python3 -c "import pyaudio; print(\"PortAudio \" + pyaudio.pa.get_version_text())"
 - python3 -c "import numpy; print(\"Numpy \" + numpy.__version__)"
 - python3 -c "import scipy; print(\"Scipy \" + scipy.__version__)"
 - python3 -c "import Cython; print(\"Cython\" + Cython.__version__)"
 - python3 -c "import OpenGL; print(\"OpenGL \" + OpenGL.__version__)"
 - /usr/local/opt/coreutils/libexec/gnubin/timeout 60s python3 friture.py
 - python3 setup.py build
 - ls -R build
 - python3 setup.py install
 - python3 setup.py py2app
