os: osx
language: python
python:
  - "3.4"
before_install:
  - brew update
  - brew install qt
  - brew install portaudio
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
# script: nosetests