language: objective-c
os: osx
python:
  - '3.6'
before_install:
  - echo $MACOSX_DEPLOYMENT_TARGET
  - brew update
  - brew install python3
  - which python3
  - python3 --version
  - brew install qt5 # this is needed to get macdeployqt, which is not in the PyPI PyQt5 wheel
install:
  - pip3 install --upgrade --user setuptools
  - pip3 install --upgrade wheel
  - pip3 install -r requirements.txt
  - pip3 install -U py2app
script:
  - python3 setup.py build_ext --inplace
  - sed -i '.bak' -e 's/file(p/open(p/g' /usr/local/lib/python3.*/site-packages/py2app/recipes/pyopengl.py
  - sed -i '.bak' -e 's/loader=loader.filename)/loader_path=loader.filename)/g' /usr/local/lib/python3.*/site-packages/macholib/MachOGraph.py
  - python3 setup.py py2app
  - "/usr/local/opt/qt5/bin/macdeployqt dist/friture.app -dmg"
  - du -hs dist/friture.app
  - du -hs dist/friture.dmg
  - export DMG_FILENAME=friture-$(python3 -c 'import friture; print(friture.__version__)')-$(date +'%Y%m%d').dmg
  - echo $DMG_FILENAME
  - mv dist/friture.dmg dist/$DMG_FILENAME
deploy:
  provider: releases
  draft: true
  api_key:
    secure: N19tf9SJmo3KluUL3DjGMxTTGaa9/qu6UNxqPtOyRu/StSzU1yeh1D8oZr+qYl6tWeqogvSWKlDw78Dp1c4Ro0IQB7ebgxT4YJGF6DeuCo1gvi1uE84Xh+Hl+Y4urS52F3ABSAHejhYhJW7XxsrA3MCiz56S7OEsuDp1u4fG8LM=
  file: dist/$DMG_FILENAME
  skip_cleanup: true
  on:
    repo: tlecomte/friture
    tags: true
