language: objective-c
os: osx
env: MACOSX_DEPLOYMENT_TARGET=10.6
python:
  - '3.4'
before_install:
  - brew update
  - ls $(brew --repo)
  - ls $(brew --repo)/Library
  - ls $(brew --repo)/Library/Taps/homebrew/homebrew-core
  - sed -i '.bak' -e 's/#{MacOS.version}/10.6/g' $(brew --repo)/Library/python3.rb
  - sed -i '.bak' -e 's/#{MacOS.version}/10.6/g' $(brew --repo)/Library/pyqt5.rb
  - brew install python3 --build-from-source
  - which python3
  - python3 --version
  - brew install qt5
  - brew install pyqt5
  - brew install portaudio
  - brew install coreutils
install:
  - pip3 install --upgrade --user setuptools
  - pip3 install --upgrade wheel
  - pip3 install --allow-external pyaudio --allow-unverified pyaudio -r requirements.txt
  - pip3 install -U py2app
script:
  - python3 setup.py build_ext --inplace
  - sed -i '.bak' -e 's/file(p/open(p/g' /usr/local/lib/python3.*/site-packages/py2app/recipes/pyopengl.py
  - sed -i '.bak' -e 's/loader=loader.filename)/loader_path=loader.filename)/g' /usr/local/lib/python3.*/site-packages/macholib/MachOGraph.py
  - python3 setup.py py2app
  - mkdir dist/friture.app/Contents/PlugIns
  - mkdir dist/friture.app/Contents/PlugIns/imageformats
  - mkdir dist/friture.app/Contents/PlugIns/platforms
  - cp -R /usr/local/opt/qt5/plugins/imageformats/libqsvg.dylib dist/friture.app/Contents/PlugIns/imageformats/
  - cp -R /usr/local/opt/qt5/plugins/platforms/libqcocoa.dylib dist/friture.app/Contents/PlugIns/platforms/
  - "/usr/local/opt/qt5/bin/macdeployqt dist/friture.app -dmg"
  #- "/usr/local/opt/coreutils/libexec/gnubin/timeout 15s open dist/friture.app"
  #- ls -R dist
  - du -hs dist/friture.app
  - du -hs dist/friture.dmg
  - export DMG_FILENAME=friture-$(python3 -c 'import friture; print(friture.__version__)')-$(date +'%Y%m%d').dmg
  - echo $DMG_FILENAME
  - mv dist/friture.dmg dist/$DMG_FILENAME
  #- ls -l dist
  #- ls -l
deploy:
  provider: releases
  draft: true
  api_key:
    secure: N19tf9SJmo3KluUL3DjGMxTTGaa9/qu6UNxqPtOyRu/StSzU1yeh1D8oZr+qYl6tWeqogvSWKlDw78Dp1c4Ro0IQB7ebgxT4YJGF6DeuCo1gvi1uE84Xh+Hl+Y4urS52F3ABSAHejhYhJW7XxsrA3MCiz56S7OEsuDp1u4fG8LM=
  file: dist/$DMG_FILENAME
  skip_cleanup: true
  on:
    repo: tlecomte/friture
    tags: true
