environment:
  matrix:
    - PYTHON: "C:/Python34"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - ps: "ls C:/Python34/"
  - ps: "ls C:/Python34/Scripts/"
  - set QTDIR=C:\Qt\5.4\mingw491_32
  - set PATH=%QTDIR%\bin;C:\MinGW\bin;%PATH%
  - choco install pyqt5 -version 5.5.0
  - choco install nsis -pre
  - nuget install portaudio
  - "%PYTHON%/Scripts/pip3 install --upgrade pip setuptools"
  - "%PYTHON%/Scripts/pip3 install --allow-external pyaudio --allow-unverified pyaudio -r requirements.txt"
  - "%PYTHON%/Scripts/pip3 install -U py2exe"
  - "%PYTHON%/python setup.py build_ext --inplace"
  - "%PYTHON%/python setup.py py2exe"
  - ps: "ls -R build"
  - "makensis.exe installer/friture-setup.nsi"
build: false
