environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON: "C:/Python34"
      PyQT: "http://downloads.sourceforge.net/pyqt/PyQt5/PyQt-5.5/PyQt5-5.5-gpl-Py3.4-Qt5.5.0-x32.exe"
      # copied from http://www.lfd.uci.edu/~gohlke/pythonlibs/3i673h27/PyAudio-0.2.8-cp34-none-win32.whl
      PyAudio: "https://www.dropbox.com/s/7um7fx768kn895v/PyAudio-0.2.8-cp34-none-win32.whl?dl=1"
      Numpy: "https://www.dropbox.com/s/v5qppu080wz3ahp/numpy-1.9.2%2Bmkl-cp34-none-win32.whl?dl=1"
      Scipy: "https://www.dropbox.com/s/mtymjhowyfogykk/scipy-0.16.0-cp34-none-win32.whl?dl=1"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - ps: "ls C:/Python34/"
  - ps: "ls C:/Python34/Scripts/"
  - "%PYTHON%/python --version"
  - "%PYTHON%/Scripts/pip3 --version"
  #- set QTDIR=C:\Qt\5.4\mingw491_32
  #- set PATH=%QTDIR%\bin;C:\MinGW\bin;%PATH%
  # chocolatey pyqt5 does not work
  #- choco install pyqt5 -version 5.5.0
  - choco install nsis -pre
  - ps: cinst 7zip.commandline
  # disable pip upgrade, seems to be broken (permission error)
  #- "%PYTHON%/Scripts/pip3 install --upgrade pip setuptools"
install:
  # PyQt
  - ps: Start-FileDownload $env:PyQT -FileName $env:temp/pyqt5_install.exe

  - ps: c:\programdata\chocolatey\bin\7z.exe x $env:temp\pyqt5_install.exe -oC:\\Python34 -r
  - ps: ls -name "C:\\Python34\\Lib\\site-packages"
  - ps: ls -name "C:\\Python34\\Lib\\site-packages\\PyQt5"
  - ps: Set-Content -Path "C:\\Python34\\Lib\\site-packages\\PyQt5\\pyuic5.bat" -Value "C:\\Python34\\python.exe -m PyQt5.uic.pyuic %1 %2 %3 %4 %5 %6 %7 %8 %9"
  - ps: Get-Content "C:\\Python34\\Lib\\site-packages\\PyQt5\\pyuic5.bat"
  - "%PYTHON%/python -c \"import PyQt5\""
  # PyAudio wheel
  - ps: Start-FileDownload $env:PyAudio -FileName $env:temp/PyAudio-0.2.8-cp34-none-win32.whl
  - "%PYTHON%/Scripts/pip3 install %temp%/PyAudio-0.2.8-cp34-none-win32.whl"
  - "%PYTHON%/python -c \"import pyaudio\""
  # Numpy wheel
  - ps: Start-FileDownload $env:Numpy -FileName $env:temp/numpy-1.9.2-cp34-none-win32.whl
  - "%PYTHON%/Scripts/pip3 install %temp%/numpy-1.9.2-cp34-none-win32.whl"
  - "%PYTHON%/python -c \"import numpy\""
  # Scipy wheel
  - ps: Start-FileDownload $env:Scipy -FileName $env:temp/scipy-0.16.0-cp34-none-win32.whl
  - "%PYTHON%/Scripts/pip3 install %temp%/scipy-0.16.0-cp34-none-win32.whl"
  - "%PYTHON%/python -c \"import scipy\""
  # Python libraries
  - "%PYTHON%/Scripts/pip3 install -r requirements.txt"
  - "%PYTHON%/Scripts/pip3 install -U py2exe"
  - "%PYTHON%/python setup.py build_ext --inplace"
  - "%PYTHON%/python setup.py py2exe"
  - ps: "ls -R build"
  - "c:\programdata\chocolatey\bin\makensis.exe installer/friture-setup.nsi"
build: false
