environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  matrix:
    - PYTHON: "C:/Python34"
      PyQT: "http://downloads.sourceforge.net/pyqt/PyQt5/PyQt-5.5/PyQt5-5.5-gpl-Py3.4-Qt5.5.0-x32.exe"
      Portaudio: "https://github.com/adfernandes/precompiled-portaudio-windows/raw/master/portaudio-r1891-build.zip"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - ps: "ls C:/Python34/"
  - ps: "ls C:/Python34/Scripts/"
  - "%PYTHON%/python --version"
  - "%PYTHON%/Scripts/pip3 --version"
  #- set QTDIR=C:\Qt\5.4\mingw491_32
  #- set PATH=%QTDIR%\bin;C:\MinGW\bin;%PATH%
  # chocolatey pyqt5 does not work
  #- choco install pyqt5 -version 5.5.0
  - choco install nsis -pre
  - ps: cinst 7zip.commandline
  # disable pip upgrade, seems to be broken (permission error)
  #- "%PYTHON%/Scripts/pip3 install --upgrade pip setuptools"
install:
  # PyQt
  - ps: Start-FileDownload $env:PyQT -FileName $env:temp/pyqt5_install.exe
  - ps: "& $env:temp/pyqt5_install.exe /S"
  - ps: "Wait-Process -Name pyqt5_install -Timeout 600"
  - "%PYTHON%/python -c \"import PyQt5\""
  # PortAudio
  - ps: Start-FileDownload $env:Portaudio -FileName $env:temp/portaudio_install.zip
  - ps: c:\programdata\chocolatey\bin\7z.exe x $env:temp\portaudio_install.zip
  - set PORTAUDIO_PATH=%CD%\portaudio-r1891-build
  # Python libraries
  - "%PYTHON%/Scripts/pip3 install --allow-external pyaudio --allow-unverified pyaudio -r requirements.txt"
  - "%PYTHON%/Scripts/pip3 install -U py2exe"
  - "%PYTHON%/python setup.py build_ext --inplace"
  - "%PYTHON%/python setup.py py2exe"
  - ps: "ls -R build"
  - "makensis.exe installer/friture-setup.nsi"
build: false
